### ISSUE TITLE
Ugly Daisy btn-ghost together with disabled

### ISSUE THREAD

**Issue by elfjes** [Uninett/argus-htmx-frontend#45]
An issue with DaisyUI. This css is created:

```css
.btn.btn-disabled,
  .btn[disabled],
  .btn:disabled {
  --tw-border-opacity: 0;
  background-color: var(--fallback-n,oklch(var(--n)/var(--tw-bg-opacity)));
  --tw-bg-opacity: 0.2;
  color: var(--fallback-bc,oklch(var(--bc)/var(--tw-text-opacity)));
  --tw-text-opacity: 0.2;
}
```
Meaning that for a button like this:

```html
<button class="btn btn-ghost" disabled>Button</button>
```

We have a `btn-ghost` that should have a fully transparent background, but when this button is disabled, a background is forced on it (primary color at 20% opacity). Since the variable is overridden inside the css block, it's also not possible to override it (otherwise we could have set a local `data-theme`), and since the selector is quite specific by targeting the `disabled` attribute, I'm not sure how to override this other than inline css. Which is not pretty
